<?php

namespace INSSET\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberEntities()
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->select('COUNT(a)');
        $queryBuilder->where('a.published = true');
        $query = $queryBuilder->getQuery();
        $result = $query->getSingleScalarResult();

        return $result;
    }

    public function findAllOthersTitles($id)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->select('a.id, a.title');
        $queryBuilder->where('a.id != :id');
        $queryBuilder->andWhere('a.published = true');
        $queryBuilder->setParameter('id', $id);
        $queryBuilder->orderBy('a.date', 'DESC');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function findAllByBlogger($blogger, $published)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->select('a');
        $queryBuilder->innerJoin('a.blogger', 'b', 'WITH', 'b.id = :id');

        if (is_null($published)){
            $queryBuilder->setParameter('id', $blogger->getId());
            $queryBuilder->orderBy('a.id', 'DESC');
        }

        else{
            $queryBuilder->where('a.published = :published');
            $queryBuilder->setParameters(array('id' => $blogger->getId(), 'published' => $published));
            $queryBuilder->orderBy('a.date', 'ASC');
        }

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
