<?php

namespace INSSET\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberEntities()
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->select('COUNT(a)');
        $query = $queryBuilder->getQuery();
        $result = $query->getSingleScalarResult();

        return $result;
    }

    public function findAllOthersTitles($id)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->select('a.id, a.title');
        $queryBuilder->where('a.id != :id');
        $queryBuilder->setParameter('id', $id);
        $queryBuilder->addOrderBy('a.id', 'DESC');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function findAllTitlesDates($blogger)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->select('a');
        $queryBuilder->innerJoin('a.blogger', 'b', 'WITH', 'b.id = :id');
        $queryBuilder->where('a.published = false');
        $queryBuilder->setParameter('id', $blogger->getId());
        $queryBuilder->addOrderBy('a.date', 'DESC');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
