<?php

namespace INSSET\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTextsDatesArticlesByBlogger($id)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->select('c.id, c.text, c.date, a.title');
        $queryBuilder->innerJoin('c.article', 'a', 'WITH', 'a.published = true');
        $queryBuilder->innerJoin('a.blogger', 'b', 'WITH', 'b.id = :id');
        $queryBuilder->setParameter('id', $id);
        $queryBuilder->orderBy('c.date', 'DESC');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
